/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "outline": "#787582",
        "on-background": "#1c1b21",
        "tertiary": "#6b5f00",
        "surface-container": "#f1ecf4",
        "on-primary-fixed-variant": "#443a90",
        "primary-fixed": "#e4dfff",
        "background": "#fcf8ff",
        "surface-container-low": "#f7f2fa",
        "on-primary-container": "#fffbff",
        "success-tint": "#E6F4EA",
        "secondary-fixed-dim": "#c7c4dd",
        "on-tertiary-fixed-variant": "#504700",
        "inverse-surface": "#313036",
        "surface-tint": "#5c52a9",
        "error-tint": "#FCE8E6",
        "error": "#ba1a1a",
        "tertiary-container": "#beac31",
        "secondary": "#5e5c72",
        "error-text": "#EF4444",
        "surface-bright": "#fcf8ff",
        "on-secondary-fixed-variant": "#464559",
        "inverse-on-surface": "#f4eff7",
        "surface": "#FFFFFF",
        "error-container": "#ffdad6",
        "tx-secondary": "#777373",
        "secondary-fixed": "#e3dff9",
        "primary-fixed-dim": "#c7bfff",
        "border": "#E5E7EB",
        "on-secondary": "#ffffff",
        "primary": "#5a50a7",
        "on-surface": "#1c1b21",
        "surface-container-high": "#ebe6ef",
        "on-tertiary-fixed": "#201c00",
        "primary-container": "#7369c2",
        "on-primary-fixed": "#170164",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e5e1e9",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "tx-primary": "#1C1A1A",
        "tertiary-fixed-dim": "#dbc84b",
        "outline-variant": "#c9c4d3",
        "surface-dim": "#ddd8e1",
        "on-secondary-container": "#646278",
        "inverse-primary": "#c7bfff",
        "surface-variant": "#e5e1e9",
        "on-surface-variant": "#474551",
        "bg-canvas": "#F3F6F6",
        "on-secondary-fixed": "#1b1a2c",
        "tertiary-fixed": "#f8e464",
        "on-tertiary-container": "#484000",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#e3dff9",
        "success-text": "#10B981",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "14px",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        lg: "24px",
        margin: "24px",
        xl: "32px",
        md: "16px",
        gutter: "16px",
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "heading-md": ["Inter", "sans-serif"],
        display: ["Geist", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["0.75rem", { fontWeight: "500" }],
        "heading-md": ["1.25rem", { lineHeight: "1.2", fontWeight: "600" }],
        "heading-md-mobile": ["1.125rem", { lineHeight: "1.2", fontWeight: "600" }],
        display: ["2rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-base": ["0.875rem", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
